CREATE TABLE IF NOT EXISTS `CATEGORIES`
(
  `ID`          BIGINT(20)  NOT NULL AUTO_INCREMENT,
  `NAME`        VARCHAR(60) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `unique` (`NAME` ASC)
);
CREATE TABLE IF NOT EXISTS `TV_SHOWS`
(
  `ID`          	BIGINT(20)    NOT NULL AUTO_INCREMENT,
  `NAME` 			VARCHAR(256)  NOT NULL,
  `SHORT_DESC` 		VARCHAR(256)  NULL DEFAULT NULL,
  `LONG_DESC` 		VARCHAR(2048) NULL DEFAULT NULL,
  `YEAR` 			YEAR(4) 	  NOT NULL,
  `RECOMMENDED_AGE` TINYINT 	  NOT NULL,
  `ADVERTISING` 	VARCHAR(256)  NULL DEFAULT NULL,
  PRIMARY KEY (`ID`)
);
CREATE TABLE IF NOT EXISTS `SEASONS`
(
  `ID`          BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `NUMBER` 		TINYINT 	 NOT NULL,
  `NAME` 		VARCHAR(256) NOT NULL,
  `TV_SHOW_ID`  BIGINT(20)   NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_SEASONS_TV_SHOW_ID`
    FOREIGN KEY (TV_SHOW_ID) REFERENCES `TV_SHOWS` (ID)
);
CREATE TABLE IF NOT EXISTS `CHAPTERS`
(
  `ID`          BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `NUMBER` 		TINYINT 	 NOT NULL,
  `NAME` 		VARCHAR(256) NOT NULL,
  `DURATION` 	TINYINT 	 NOT NULL,
  `SEASON_ID`  BIGINT(20)   NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_CHAPTERS_SEASON_ID`
    FOREIGN KEY (SEASON_ID) REFERENCES `SEASONS` (ID)
);
CREATE TABLE IF NOT EXISTS `ACTORS`
(
  `ID`          BIGINT(20)  NOT NULL AUTO_INCREMENT,
  `NAME`        VARCHAR(60) NOT NULL,
  `DATE_OF_BIRTH`        DATETIME NULL,
  `COUNTRY`        VARCHAR(60) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `uniqueActorName` (`NAME` ASC)
);
CREATE TABLE IF NOT EXISTS `ACTORS_CHAPTER`
(
  `ID`          BIGINT(20)  NOT NULL AUTO_INCREMENT,
  `ACTOR_ID`          BIGINT(20)  NOT NULL,
  `CHAPTER_ID`        BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID`),
	CONSTRAINT `FK_AC_ACTOR_ID`
    FOREIGN KEY (ACTOR_ID) REFERENCES `ACTORS` (ID),
   CONSTRAINT `FK_AC_CHAPTER_ID`
    FOREIGN KEY (CHAPTER_ID) REFERENCES `CHAPTERS` (ID)
);
CREATE TABLE IF NOT EXISTS `AWARDS`
(
  `ID`          BIGINT(20)  NOT NULL AUTO_INCREMENT,
  `NAME`        VARCHAR(30) NOT NULL,
  `DESCRIPTION`        VARCHAR(60) NULL,
  PRIMARY KEY (`ID`)
);
CREATE TABLE IF NOT EXISTS `AWARD_CATEGORIES`
(
  `ID`          BIGINT(20)  NOT NULL AUTO_INCREMENT,
  `DESCRIPTION`        VARCHAR(100) NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `TV_SHOW_AWARDS`
(
  `ID`          BIGINT(20)  NOT NULL AUTO_INCREMENT,
  `TV_SHOW_ID`          BIGINT(20)  NOT NULL,
  `AWARD_ID`        BIGINT(20) NOT NULL,
  `AWARD_CATEGORY_ID`        BIGINT(20) NOT NULL,
  `YEAR` 			YEAR(4) 	  NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE (TV_SHOW_ID, AWARD_ID,AWARD_CATEGORY_ID,YEAR),
	CONSTRAINT `FK_TVSA_TV_SHOW_ID`
    FOREIGN KEY (TV_SHOW_ID) REFERENCES `TV_SHOWS` (ID),
   CONSTRAINT `FK_TVSA_AWARD_ID`
    FOREIGN KEY (AWARD_ID) REFERENCES `AWARDS` (ID),
       CONSTRAINT `FK_TVSA_AWARDS_CATEGORIES_ID`
    FOREIGN KEY (AWARD_CATEGORY_ID) REFERENCES `AWARD_CATEGORIES` (ID)
);

CREATE TABLE IF NOT EXISTS `TV_SHOW_CATEGORIES`
(
  `ID`          BIGINT(20)   NOT NULL AUTO_INCREMENT,
  `TV_SHOW_ID` 		BIGINT(20) 	 NOT NULL,
  `CATEGORY_ID` 		BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `FK_TV_SHOW_CATEGORIES_TV_SHOW_ID`
    FOREIGN KEY (TV_SHOW_ID) REFERENCES `TV_SHOWS` (ID),
   CONSTRAINT `FK_TV_SHOW_CATEGORIES_CATEGORY_ID`
    FOREIGN KEY (CATEGORY_ID) REFERENCES `CATEGORIES` (ID)
);