INSERT INTO TV_SHOWS(ID, NAME, SHORT_DESC, LONG_DESC, YEAR, RECOMMENDED_AGE) VALUES 
	(1, 'TvShow1', 'Descripción corta', 'Descripción larga', '2012', 16); 

INSERT INTO AWARDS(ID, NAME, DESCRIPTION) VALUES 
	(1, 'Oscar','también llamado Academy Award'),
	(2, 'Globo de oro','también llamado Academy Award');

INSERT INTO AWARD_CATEGORIES(ID, DESCRIPTION) VALUES 
	(1, 'MEJOR ACTOR PROTAGONISTA');
	
INSERT INTO TV_SHOW_AWARDS( TV_SHOW_ID, AWARD_ID,AWARD_CATEGORY_ID, YEAR) VALUES 
	(1, 1 , 1, 2010),
	(1, 2 , 1, 2010);